### ISSUE TITLE
Empty p-dropdown is not shown

### ISSUE THREAD

**Issue by aozkesek** [primefaces/primeui#104]
Please find more detail from this link;

http://forum.primefaces.org/viewtopic.php?f=16&t=44205

**Comment by cagataycivici** [comment]
Great fix, thanks but I just see a visual issue, do you experience the same?
<img width="219" alt="screen shot 2016-01-12 at 17 19 20" src="https://cloud.githubusercontent.com/assets/686247/12267414/ab6fb35e-b950-11e5-96f7-7e9341cd5073.png">

**Comment by aozkesek** [comment]
Yes indeed Cagatay.  I also tried old way that is calling puidropdown function, the result is same. So I do not go deep, I do not like css, I prefer to use 3rd party, like PrimeUI.
