### ISSUE TITLE
Add reload method to DataTable

### ISSUE THREAD

**Issue by qwerlowski** [primefaces/primeui#107]
Good day. Could you please add new method "refresh" to datatable, paginator widgets.

**Comment by Mrtcndkn** [comment]
What it should do?

**Comment by qwerlowski** [comment]
It should reload data, send request to server and refresh datasource. because there could be changes and new records, something deleted in server. so it's essential to reload data again.

**Comment by cagataycivici** [comment]
refresh is reserved in jQuery UI widget factory so we can add reload. Will do it for 3.0.1.

**Comment by qwerlowski** [comment]
Thanks. I got the example from http://www.demo.znetdk.fr/ site which is from http://www.primefaces.org/primeui/. There both paginator and datatable has reload method. You should get number of new records from server and reset paginator, reload data.

**Comment by cagataycivici** [comment]
I'm working on it, also will add support to PrimeElement.

**Comment by cagataycivici** [comment]
Usage is;

```js
$('dt').puidatatable('reload')
```

and for PrimeElement

```js
document.getElementById('dt').reload()
```

**Comment by qwerlowski** [comment]
Thanks a lot

**Comment by Anceloth** [comment]
Thanks a Lot!!!
