### ISSUE TITLE
WebComponent for Calendar

### ISSUE THREAD

**Issue by fenglinyushu** [primefaces/primeui#137]
I have see there are some new web components such as calendar and other is Primefaces demo.
When we can use it ?
Thanks!
 
The demo at 
http://www.primefaces.org/showcase/index.xhtml
we need the web component such as Calender,...

**Comment by cagataycivici** [comment]
I think we can wrap jquery ui datepicker as a web component. I also thought the same. Thank you for the feedback. We'll plan it for 3.0.2 probably.

**Comment by fenglinyushu** [comment]
Thanks for reply! There are some more components at http://www.primefaces.org/showcase/index.xhtml

**Comment by Mrtcndkn** [comment]
https://github.com/primefaces/primeui/commit/903d4a7645311b70b81d61391685020b73aca009
