### ISSUE TITLE
MultiSelect Widget

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeui#15]
Create a new widget based on p:selectCheckboxMenu.

**Comment by aozkesek** [comment]
Hi Cagatay,

I see this issue is waiting for so long, and still no one is assigned to this.  You may check this out,

[https://github.com/aozkesek/CheckboxSelect.git](url) 

I do not well with css staff, I've just focused functional.  

br,

**Comment by cagataycivici** [comment]
Thanks, the url is broken though.

**Comment by aozkesek** [comment]
My mistake, here is the fixed,

[https://github.com/aozkesek/CheckboxSelect.git](https://github.com/aozkesek/CheckboxSelect.git)

**Comment by cagataycivici** [comment]
We'll check, thank you @aozkesek .
