### ISSUE TITLE
getSelection in puidatatable does not work if first row is selected

### ISSUE THREAD

**Issue by trickysan** [primefaces/primeui#153]
If the first row in puidatatable is selected, the call of "getSelection" returns an empty result.
It only works starting with the second row.

**Reproduction of issue:**
- Select first row on table "Single Selection": http://www.primefaces.org/primeui/#datatableSelection
- Call: `$('#tblsingle').puidatatable('getSelection')`
Result: []
- Select second row
- Call `$('#tblsingle').puidatatable('getSelection')`
Result : [Object { vin="af4407ea",  brand="Honda",  year=1964,  mehr..

**Comment by cagataycivici** [comment]
Replicated

**Comment by aozkesek** [comment]
Hi Cagatay,  
The fix seems easy,  I've tested this fix on datatableselection.html with both single and multiple, and on datatable.html with remote lazy table after add single selection and then multiple selection feature to it.

Would you review, test too?

I've just changed greater than operator to greater than or equal operator in datatable.js in getSelection function ;
 
				for(var i = 0; i < this.selection.length; i++) {
					 if(this.data.length > this.selection[i]-first && this.selection[i]-first >= 0) {


The only thing I concern is what happen on multiple selection maden from different page of lazy, current situation gets only selections of the current page,

**Comment by trickysan** [comment]
The fix from @aozkesek works for me as expected.

**Comment by cagataycivici** [comment]
I'm rewriting the selection impl to fix this and a couple of other issues.

**Comment by cagataycivici** [comment]
Fixed for 4.1.1.
