### ISSUE TITLE
ajax support to DropDown widget

### ISSUE THREAD

**Issue by qwerlowski** [primefaces/primeui#156]
Could you please add ajax data support into widget "DropDown". This is very very important.

**Comment by qwerlowski** [comment]
Good day. Could you consider this improvement.

**Comment by cagataycivici** [comment]
Could you please clarify what you mean by ajax support?

**Comment by qwerlowski** [comment]
DropDown should load data like "datasource" option in DataTable. For example like in DataTable "datasource: function(callback)" in order i could send ajax request and fill it. I think it is essential.

**Comment by qwerlowski** [comment]
Good day. Could you consider this improvement.

**Comment by cagataycivici** [comment]
Great idea, we'll do it.

**Comment by Mrtcndkn** [comment]
We added both remote data and remote url from now on you can use both of the methods.
