### ISSUE TITLE
Bug on button methods (enable and disable)

### ISSUE THREAD

**Issue by ograndebe** [primefaces/primeui#164]
The methods enable and disable on puibutton not working properly

I fixed it on my project
`
        disable: function() {
            this._unbindEvents();
            this.element.prop('disabled',true);
            this.element.addClass('ui-state-disabled');
        },
        
        enable: function() {
            if(this.element.prop('disabled')) {
                this._bindEvents();           
                this.element.prop('disabled', false).removeClass('ui-state-disabled');
            }
        },
`

**Comment by cagataycivici** [comment]
Fixed for 3.0.2
