### ISSUE TITLE
I use "removeAllOptions" and "addOption" in Dropdown, but it not work well

### ISSUE THREAD

**Issue by fenglinyushu** [primefaces/primeui#189]
can you send me a demo? 
LeeBillows@gmail.com
thanks! 

and another question

the "black" point in radio button not at the center position of circle

**Comment by Mrtcndkn** [comment]
In live demo they are all working as expected.Can you send your code what is wrong in your case and i'll try to replicate locally.

About radiobutton we will fix it immediately.

**Comment by fenglinyushu** [comment]
I have got it, thanks
