### ISSUE TITLE
How to "removeAllOptions" and "addOption" in ListBox?

### ISSUE THREAD

**Issue by fenglinyushu** [primefaces/primeui#193]
How to "removeAllOptions" and "addOption" in ListBox?

**Comment by Mrtcndkn** [comment]
ListBox don't have those options at this point.

**Comment by fenglinyushu** [comment]
Thanks

**Comment by Mrtcndkn** [comment]
https://github.com/primefaces/primeui/commit/c1408f3924a64ec37624ccc9e4bc8b061e992105
