### ISSUE TITLE
A bug in the methods of CheckBox. "unselect" should be "uncheck" 

### ISSUE THREAD

**Issue by fenglinyushu** [primefaces/primeui#194]
A bug in the methods document of CheckBox : "unselect" should be "uncheck"

**Comment by fenglinyushu** [comment]
And how get the status of radiobutton ? thanks

**Comment by fenglinyushu** [comment]
And in radiobutton.js, the "_isChecked" should be "isChecked" like checkbox.js ?

**Comment by fenglinyushu** [comment]
And should add "check" and "uncheck" in methods like checkbox.js?

**Comment by cagataycivici** [comment]
Fixed the doc for checkbox, please create separate issue for radio enhancements.
