### ISSUE TITLE
Datatable filter and getSelection returns wrong data

### ISSUE THREAD

**Issue by SuperSonicFlea** [primefaces/primeui#198]
Hi,
When filtering a table with single selection enabled, getSelection method returns the object for the row number as if it is not filtered. 

e.g. Table has 10 items, after filter show 3 items, select the second item and it return the data for second item out of the original 10.

I may be doing some wrong as I am new to web development but so far its consistent.

Thank you.

**Comment by cagataycivici** [comment]
This is known issue that will be address in 4.1.1 next week.

**Comment by cagataycivici** [comment]
Fixed for 4.1.1.
