### ISSUE TITLE
Error when trying to filter or sort a column in dataTable

### ISSUE THREAD

**Issue by consu3sg** [primefaces/primeui#202]
When I try to sort or filter a column  i get the following error:
"Uncaught TypeError: Cannot read property 'update' of undefined"
![untitled](https://cloud.githubusercontent.com/assets/14964375/13383234/8f5e78be-de65-11e5-92d2-00d75de0ce17.png)

**Comment by cagataycivici** [comment]
Can you please provide your sample code? Which version do you have?

**Comment by consu3sg** [comment]
I've just found out what was going on ! The problem has nothing to with PrimeUI.
The problem was in the way I included the jQuery files in my View.

Thank for your attention !

**Comment by cagataycivici** [comment]
Thank you for the update.
