### ISSUE TITLE
How can I test PrimeUI with locatehost?

### ISSUE THREAD

**Issue by fenglinyushu** [primefaces/primeui#217]
I download the primeui-mster.zip  and  unzip it. 
when i double click the index.html, it viewed normally,
But when i click the components' link (such as inputText) , it no reaction. 
Can you help me ? 
I have not gulp

Thanks

**Comment by Mrtcndkn** [comment]
Try to use it with npm.
1. npm install
2. npm start
It will run the primeui with lite-server on localhost:3000

**Comment by fenglinyushu** [comment]
Thanks

**Comment by cagataycivici** [comment]
I guess you also need to do gulp build-all before npm-start
