### ISSUE TITLE
puiautocomplete initialization error

### ISSUE THREAD

**Issue by ritchiecarroll** [primefaces/primeui#220]
The autocomplete can fail during initialization when calling on('keydown.puiautocomplete'... since items array has yet to be defined.

Error: Cannot read property 'filter' of undefined on line 609

**Comment by Mrtcndkn** [comment]
It seems i can't replicate your issue i'm not getting any errors calling on('keydown.puiautocomplete'...

**Comment by ritchiecarroll** [comment]
Here is an example:
http://jsfiddle.net/ritchiecarroll/36L1fp8s/1/

**Comment by ritchiecarroll** [comment]
I am having trouble replicating within fiddle - this seems to be a timing issue with lot's of other Javascript running. The pull request resolves by simply making sure the elements being used are properly initialized, here is a screen capture of the error on the line:

<img width="754" alt="capture" src="https://cloud.githubusercontent.com/assets/9202752/14229979/01c68c3c-f90c-11e5-8dd2-48b3b9da3c62.PNG">

**Comment by StephenCWills** [comment]
While working on the jsfiddle to reproduce this issue, we discovered the page was missing jquery-ui.css. Adding the stylesheet to the page fixed the issue so this was a false alarm.
