### ISSUE TITLE
Panel - allow custom content in header and footer

### ISSUE THREAD

**Issue by djmj** [primefaces/primeui#227]
We are missing functionality to define custom content in header. Footer is not existent.

Maybe allow optional to include header and footer as childs something like this:

    <div id="panel">
        
        <div class="GreenBack"><i class="fa fa-user"/> User</div>
        <div>content</div>
        <div>footer</div>
    </div>

**Example:**

In our adamantium page we often need to recreate DOM panels since we need custom footer, header with icon and different background color. On our main page we have 5 panels with different header background colors and footers: http://www.deloma.de/agency

**Comment by Mrtcndkn** [comment]
It is in progress both footer header and custom content for them will be available soon.

**Comment by djmj** [comment]
Thank you :) PrimeUI Rocks!, especially in combination with PrimeFaces and CMS.

**Comment by Mrtcndkn** [comment]
Thanks for your thoughts :)

**Comment by djmj** [comment]
I am not really a fan of putting html into javascript variables just for simple styling. 
It is much harder to maintain and if html gets to complex it will get a mess to put it into a variable. 

Declarative approach using data attribute is much cleaner:

<div id="panel">
    
    <div class="GreenBack" data-facet="header"><i class="fa fa-user"/>User</div>
    <div data-facet="content">content</div>
    <div data-facet="footer">footer</div>
</div>

You should reconsider this. I also don't use PrimeUI datatable since its a mess to use with javascript (#243).
