### ISSUE TITLE
 DataTable with Array Prototype Error

### ISSUE THREAD

**Issue by ritchiecarroll** [primefaces/primeui#233]
When the Array class has any prototype extension, paging in a PUI data table will report an exception (see below).

Fiddle to replicate:
http://jsfiddle.net/ritchiecarroll/f6gdn9to/

![image](https://cloud.githubusercontent.com/assets/9202752/14360561/fd0ca2fa-fcc4-11e5-9573-c8b685d5ceb9.png)

**Comment by cagataycivici** [comment]
@Mrtcndkn Please take over.
