### ISSUE TITLE
Outdated gradient syntax

### ISSUE THREAD

**Issue by brian428** [primefaces/primeui#240]
Using primeui, autoprefixer flagged a warning about outdated gradient syntax in the theme CSS. Basically, instead of `background-image: linear-gradient(top, #ffffff, #e6e6e6);`, the recommended syntax is: `background-image: linear-gradient(to bottom, #ffffff, #e6e6e6);`

(Full details at: https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient#Values).

Obviously this isn't a big issue but I thought I'd let you know so the themes can be updated when you have a chance.

**Comment by Mrtcndkn** [comment]
https://github.com/primefaces/primeui/commit/da7cdd5a278ec51e182270c2ce2a9ec93a655053
