### ISSUE TITLE
ui-accordion-content overflow:auto causes scrollbar on dropdown/menu

### ISSUE THREAD

**Issue by mdonato7** [primefaces/primeui#251]
Expanding a primeng dropdown or menu in an accordion currently causes the resulting popup to appear inside the accordion with a scrollbar, rather than popping over the accordion.

Switching it to `overflow: initial` fixes this issue, see primefaces/primeng#291

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/1869
