### ISSUE TITLE
Timepicker 'Now' Function Causes NaN

### ISSUE THREAD

**Issue by names144** [primefaces/primeui#252]
The issue seems to be fixed in the current release: [http://trentrichardson.com/examples/timepicker/jquery-ui-timepicker-addon.js](http://trentrichardson.com/examples/timepicker/jquery-ui-timepicker-addon.js)

Related to PrimeNG: [https://github.com/primefaces/primeng/issues/589](https://github.com/primefaces/primeng/issues/589)

**Comment by cagataycivici** [comment]
PrimeNG has its own native calendar, so this issue is obselete now.
