### ISSUE TITLE
QuickStart, PrimeElements and more

### ISSUE THREAD

**Issue by Med-All** [primefaces/primeui#261]
I'm new to PrimeUI and I have followed steps form the main PrimeUI page and QuickStart.

From there

> In order to use PrimeElements, add X-Tag library that also includes the pollyfill for custom elements.

```
<script type="text/javascript" src="%PATH%/x-tag-core.min.js"></script>
<script type="text/javascript" src="%PATH%/primeelements-3.0.js"></script>
```

From where should I download primeelements-3.0.js file when the main PrimeUI package doesn't contain it?

Next - Web Components: PromeElements

I have tried to get some examples to work but I had no luck. For an example 

```
<button type="button" is="p-button" icon="fa-external-link" onclick="document.getElementById('dlgelement').show()" >Show</button>
 
<p-dialog id="dlgelement" title="Dialog Header" modal showeffect="fade" hideeffect="fade" draggable resizable>
    <p>Dialog content here.</p>
</p-dialog>
```

dialog window got open but I'm not able to close it - getting errors:

```
primeui.min.js:3 Uncaught TypeError: t(...).zIndex is not a function
    at HTMLDocument.<anonymous> (http://localhost/lib/primeui.min.js:3:9501)
    at HTMLDocument.dispatch (http://localhost/lib/jquery.js:5226:27)
    at HTMLDocument.elemData.handle (http://localhost/lib/jquery.js:4878:28)
```
also I have tried other [examples](http://www.primefaces.org/primeui) and it came that I'm able to get to work about 1/4 of them. All the rest simple is not working at all or throwing errors all around.

I'm running latest jQuery and jQuery UI

Thanks for help.

**Comment by cagataycivici** [comment]
Please use PrimeUI forum for questions, thank you.
