### ISSUE TITLE
Component configurator for CMS text-editor

### ISSUE THREAD

**Issue by djmj** [primefaces/primeui#274]
Currently you need someone with decent html knowledge to create PrimeUI content. Things like wordpress or the number 1 slider plugin [https://codecanyon.net/item/slider-revolution-jquery-visual-editor-addon/13934907](url) have high success since they became more user-friendly allowing visual editors or at least configurators to dynamically create content without the need of good html and javascript knowledge.

If for each PrimeUI component a simple configurator or a visual editor would be available this could target a new "normal" user audience too.

PrimeFaces with PrimeUI for dynamic CMS content is a perfect combination. But you still need someone to write the PrimeUI markup and code. With an editor any person could configure it with some clicks which reduces costs.

The markup generator would speed up PrimeUI usage. Searching the html and make the previously created components updateable is more the challenge.

**Comment by cagataycivici** [comment]
Thank you, we'll consider this.
