### ISSUE TITLE
Dialog enhancement: Provide ability to set iframe 'title' attribute (like Lightbox provides)

### ISSUE THREAD

**Issue by paulspinelli** [primefaces/primeui#275]
The dialog component constructs an iframe; however, the component does not provide a means to set the 'titl'e attribute of the resulting iframe. Due to Section 508 requirements, the iframe 'title' attribute must contain descriptive text. The lightbox component does provide such an attribute (iframeTitle).

**Comment by cagataycivici** [comment]
Please use PrimeFaces issue tracker, this is for PrimeUI.
