### ISSUE TITLE
Toggle button should have icon only capability

### ISSUE THREAD

**Issue by dragonzone** [primefaces/primeui#29]
If not label is set, the on/off icon should be used instead.

**Comment by cagataycivici** [comment]
I agree, will do for 2.0.1.

**Comment by cagataycivici** [comment]
Thinking again, label should be mandatory otherwise it becomes no different than a checkbox, still workaround is;

```js
$('#basic').puitogglebutton({
                onLabel: '&nbsp',
                offLabel: '&nbsp',
                onIcon: 'fa-check-square',
                offIcon: 'fa-square'
            });
```

**Comment by dragonzone** [comment]
The problem with the "&nbsp;" is that the icon will not be align center. There are cases where I would want the label to be separate and just the toggle with the icon, which needs to be centered.
