### ISSUE TITLE
DataTable should use max-height for scrollable

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeui#30]
Posted at our forum;

I think that scrollable datatable scrollBody should have line

this.scrollBody.height(this.options.scrollHeight);

replaced with: 

this.scrollBody.css('max-height', this.options.scrollHeight);

For example if scrollHeight == 500 then datatable with just one row looks really weird. It is far better to use max-height in script or at least give it on option. In my case, having big empty table with one row is just unacceptable. So either it should be on option or always max-height. I think that even in Primfaces you have max-height, not height.

**Comment by vsrihari9** [comment]
How is it fixed? I'm using scrollHeight attribute and still see this issue?
