### ISSUE TITLE
puidialog when set to draggable=true, and drag to another location beside default center, will reset dialog back to center before letting it to resize again.

### ISSUE THREAD

**Issue by dragonzone** [primefaces/primeui#32]
In the dialog.html, if you change draggable to "true", and run it you will see that: When you click the "Show" button, the dialog comes up, then try dragging the dialog to the left or right side, after that try resizing, you will the dialog will go back to the center and the mouse is still at the left or right hand side but still let u continue resize the dialog.

**Comment by cagataycivici** [comment]
I can't replicate at;

http://www.primefaces.org/primeui/#dialog

Runs on 2.2.RC1
