### ISSUE TITLE
DataTable selecting from iPhone (iOS8)

### ISSUE THREAD

**Issue by mathparks** [primefaces/primeui#39]
The selecting of a row of data in a DataTable is not working from iPhone iOS 8. I have confirmed that using my phone on the PrimeUI example page it does not work either.

http://www.primefaces.org/primeui/index.html#datatable

Posted on forum and was requested to log bug.  Thus this.

Reference:
http://forum.primefaces.org/viewtopic.php?f=16&t=42997&sid=6d7941546044430f8927c8e97f51a34a

Thank you
Matthew C. Parks

**Comment by cagataycivici** [comment]
Fixed for 2.2
